---
name: JSII Publish
description: Builds and publishes JSII packages
author: deemes79@googlemail.com
branding:
  icon: upload-cloud
  color: orange
runs:
  using: docker
  image: docker://udondan/jsii-publish:0.10.0
inputs:
  BUILD_SOURCE:
    description: Indicates if the source should be build (tsc)
    default: false
  BUILD_PACKAGES:
    description: Indicates if the packages should be build (jsii)
    default: false
  VERSION:
    description: If set, the version in `package.json` will be updated with this value
    required: false
  NPM_TOKEN:
    description: Your publish token for npm. If passed, package will be published to npm
    required: false
  PYPI_TOKEN:
    description: Your publish token for PyPI. If passed, package will be published to PyPI
    required: false
  NUGET_TOKEN:
    description: Your publish token for NuGet. If passed, package will be published to NuGet
    required: false
  GITHUB_TOKEN:
    description: Your publish token for GitHub. If passed, Maven package will be published to Github
    required: false
  GITHUB_REPOSITORY:
    description: GitHub repository path. OWNER/REPO, e.g. `udondan/jsii-publish`. You can just pass in `{{ github.repository }}`
    required: false
  DEBUG:
    description: Enables debug mode
    default: false
  NPM_OPTIONS:
    description: Command options to append to the `npm publish` command
    required: false
  PYPI_OPTIONS:
    description: Command options to append to the `twine upload` command
    required: false
  NUGET_OPTIONS:
    description: Command options to append to the `dotnet nuget push` command
    required: false
