---
name: Test image functionality

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(cat VERSION)1$(( $RANDOM % 1000 ))

      - name: Print version
        run: echo ${{ steps.get_version.outputs.VERSION }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag jsii-publish:current

      - name: Build the test package
        run: >-
          docker run
          --workdir /workdir
          --volume ${PWD}/test:/workdir
          --env VERSION=${{ steps.get_version.outputs.VERSION }}
          --env BUILD_SOURCE=true
          --env BUILD_PACKAGES=true
          jsii-publish:current

      - name: Publish npm package
        run: >-
          docker run
          --workdir /workdir
          --volume ${PWD}/test:/workdir
          --env NPM_TOKEN
          jsii-publish:current
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
