---
name: Test image functionality

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag jsii-publish:current
